### ISSUE TITLE
license copyright year not up to date

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-sources#13]
Does the copyright year need to be updated in license.pdf, at the top of all the *.shen files and in the string at the bottom of make.shen?

A thought I had was to make license.pdf just a .txt file, and have the code in make.shen read in license.txt to inject into KL files.

Judging by the fact that the license is in every file, these things are considered important.

**Comment by rkoeninger** [comment]
I guess this is whatever, so I'm closing it.

**Comment by tizoc** [comment]
@rkoeninger sorry, I just have no idea about this, I sometimes update the year in my own code, but the difference is that the name in the copyright is my own, not sure how different it is in this case (or if the year matters at all).
