### ISSUE TITLE
Basic dictionaries

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#20]
# Basic dictionaries discussion

This is based on an old thread[1] from the mailing list started by @gravicappa.

Creating it because it was never resolved, and I didn't want it to get lost.

@gravicappa are you still interested in this or was overriding `hash` good enough?

## Current implementations

None in ports, but see the first email in the thread for @gravicappa's implementation for the Common Lisp port.

## Motivation

Shen uses many assoc lists and ad-hoc hash tables internally for doing bookkeeping and associating data, but there is no well defined interface for it.

Many of those operations can be implemented with much better performance using port's native hash tables (or maps) functionality, but since there is no well defined interface internally, doing so is not trivial.

This proposal tries to solve that by creating a simplistic default implementation using the already existing code, by normalizing it so that it is easier to overwrite by ports (and defaulting back to the regular implementations if ports don't provide one).

## Proposed interface

Ports would have to implement the following functions:

- `(make-dict Size)` — returns dictionary object
- `(dict-> Dict Key Value)` — stores value.
- `(<-dict Dict Key)` — retrieves value if it exists or throws an error.
- `(<-dict/or Dict Key Default)` -- like `<-dict` but returns the result of thawing `Default` instead of throwing an error when the key is missing.
- `(dict-rm Dict Key)` — removes value from a dictionary. 
- `(dict-fold Dict Func Init)` — iterates over the dictionary passing `Key` and `Value` to `Func` (with signature `{Key --> Value --> Accum --> Result}`, accumulating the result starting with `Init`.

If they are not provided, defaults are used, with dictionaries being implemented as assoc lists.

With `dict-fold` the following functions are trivial, but there is no reason ports can't provide their own native implementations:

```shen
(define dict-keys
  Dict -> (dict-fold Dict (/. Key Val Acc [Key | Acc]) []))

(define dict-values
  Dict -> (dict-fold Dict (/. Key Val Acc [Val | Acc]) []))

(define dict->alist
  Dict -> (dict-fold Dict (/. Key Val Acc [[Key | Val] | Acc]) []))

(define dict-size
  Dict -> (dict-fold Dict (/. Key Val Acc (+ 1 Acc)) 0))
```

### Hash tables used internally

- Shen's hash table implementation for put/get: https://github.com/Shen-Language/shen-sources/blob/master/sources/sys.shen#L290-L322
- Shen's hash implementation (overriding this with native implementation = big speedups): https://github.com/Shen-Language/shen-sources/blob/master/sources/sys.shen#L324-L344

Then all uses of put/get, like:

- https://github.com/Shen-Language/shen-sources/blob/0e3dbae4a18a90ff71faadeb9e05a38f07b5ff39/sources/declarations.shen#L89-L95

### Uses of assocs:

- https://github.com/Shen-Language/shen-sources/blob/89e08b8d5987f8d48f475432c8c112a2f731e3b4/sources/core.shen#L267-L272
- https://github.com/Shen-Language/shen-sources/blob/89e08b8d5987f8d48f475432c8c112a2f731e3b4/sources/core.shen#L280-L297
- https://github.com/Shen-Language/shen-sources/blob/89e08b8d5987f8d48f475432c8c112a2f731e3b4/sources/t-star.shen#L166-L167

### Places where linear searches over long lists are used that could benefit from faster alternatives:

- https://github.com/Shen-Language/shen-sources/blob/89e08b8d5987f8d48f475432c8c112a2f731e3b4/sources/core.shen#L48-L49
- https://github.com/Shen-Language/shen-sources/blob/0e3dbae4a18a90ff71faadeb9e05a38f07b5ff39/sources/declarations.shen#L128-L135

`sysfunc?` in particular is quite slow for being a function that is called so often. It is one of the functions I override in shen-scheme to improve compilation times.

## Notes:

As I noted in the mailing list thread[1], a major speedup is obtained by just using a native implementation of the `hash` function instead of having to do what is proposed here. That doesn't mean that it would not be beneficial to also provide a standarized interface for making it easy for ports to overwrite with native implementations. Also, as Ramil mentioned, not all platforms that implement hash tables provide direct access to their hashing function (Javascript for example).

## References
- [1] https://groups.google.com/d/msg/qilang/_ybsm0MDXgE/giT1tA_k_MsJ

**Comment by gravicappa** [comment]
Overriding `hash` works on a limited number of platforms (I am unable to name more than CL and some Scheme implementations). So I think that having `dict` is still useful.

**Comment by tizoc** [comment]
@gravicappa others that come to mind right now: Python, Ruby, Java, OCaml

But doesn't matter, all that means is that such ports could get away with just overriding `hash`, it is still a good idea to have a clean interface defined and let other implementations who can't do that (like Javascript, and maybe Lua?) do their thing too.

If you think the interface I defined here is fine, I can write a PR (probably this weekend) and submit it for review.

**Comment by gravicappa** [comment]
Being able to operate native dictionaries is extremely useful for JavaScript, Python, (maybe Ruby, Lua, etc).

I'm fine with the defined interface except that restrictions on `Key` parameter require some thought. To play safe I think that the key must be a string.

**Comment by tizoc** [comment]
@gravicappa yes, a string is what Shen uses right now, and the plan is to just normalize the code a bit to make it easy to overwrite (I don't think those functions should be exposed yet, I would wait a bit for that and keep them internal for now). Just in case I added a new parameter to the dictionary constructor, it now looks like `(make-dict Size HashFunc)`.

**Comment by tizoc** [comment]
Sorry, to clarify, when *hashing* Shen makes everything into a string, but the keys can still be anything.

@gravicappa do you think you will have any problem with this in Javascript? can't you just use Map objects instead of regular objects? (seems safer and cleaner)

**Comment by tizoc** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by gravicappa** [comment]
Using regular objects in JavaScript was primary reason I started thinking about dict type. 

After some research I think that restricting key type as strings would simplify only implementing dict on low-level platform. And for that Shen has `str` function. So restriction case may be closed.

**Comment by tizoc** [comment]
Responding to https://github.com/Shen-Language/shen-sources/pull/25#issuecomment-283125032

Having a default handler is still desired even if you can check for the existence of a key, because this lets you both check and fetch in a single lookup, while the alternative is having to lookup twice. `has-key?` is also trivially implementable on top of `<-dict` and with no loss in performance.
