### ISSUE TITLE
shen.shen renamed?

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-sources#27]
I updated the shen sources in my [ShenSharp project](https://github.com/rkoeninger/ShenSharp/commit/97653d5516fa6491f09a7933a7b61d271e9a7000) and re-built the kl using the standard SBCL implementation of Shen (in case there's still something weird about mine).

After that, the function `(shen.shen)` (the function that runs the repl) doesn't exist and now it's referred to as just `(shen)`.

Was this a deliberate change? I was using 19.2 before and I don't see anything about it in the changelog.

**Comment by tizoc** [comment]
@rkoeninger yes, it was not really renamed, it was more a side-effect of recompiling the Shen sources to KLambda using a newer version of Shen. See this comment for details https://github.com/Shen-Language/shen-sources/pull/2#issuecomment-251231066

**Comment by tizoc** [comment]
I think the change happened in Shen 19, I'm not entirely sure. I'm now thinking that It is possible that such behavior was not intended and is a bug, it is something to investigate.

**Comment by tizoc** [comment]
@rkoeninger I just sent an email to the mailing list so that Mark can tell us if it was intentional or not.

**Comment by tizoc** [comment]
@rkoeninger ok, this is indeed a bug (Mark hasn't answered but after playing with this a bit I concluded that it is a bug, see my messages on the list). Will push the fix in a few minutes.
