### ISSUE TITLE
Command line access

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#3]
# Command line access discussion

The scope of this discussion is only about how ports should make it the command line invocation fragments available for Shen to use, there are other discussions related to this but it is better if we keep those in separate issues. This discussion started in the mailing list when Neal sent a patch[1] that adds command line handling to the Common Lisp port.
## Current implementations
-  https://github.com/tizoc/shen-scheme#command-line-arguments

_TODO: add others_
## Representation

I propose that the command line fragments be represented by a 1-or-more elements list, with the first element being the command name (with some default, probably just `"(shen)"`), equivalent to `argv[0]` on posix systems. The remaining elements would be the extra arguments.

Examples:
- `shen -l file.shen` -> `["shen" "-l" "file.shen"]`
- `shen` -> ["shen"]
- `shen-ruby` -> ["shen-ruby"]
## Access

There are many possible ways the port could make the command line fragments available to Shen, some that come to my mind are:
### Option 1. Have the port set a global variable to the list of command line parts (like with i/o ports)

Something like `(set *command-line-fragments* [<argument list>])` on startup.

**Pros**
_TODO_

**Cons**
_TODO_
### Option 2. Have the port provide a `(command-line)` primitive

This primitive would return the fragments used to invoke the command with the representation discussed earlier.

`(command-line)` would return `["shen" "arg1" "arg2" ...]`.

**Pros**
_TODO_

**Cons**
_TODO_
## Notes
- Command line access doesn't make sense for all ports (elisp and javascript when running in the browser are two examples). In such cases the list could just default to a single element list containing the name of the port.
## References
- [1] https://groups.google.com/forum/#!topic/qilang/4AxtzPlwi74

**Comment by tizoc** [comment]
Solved in #37

**Comment by rkoeninger** [comment]
I'm a little confused about the details of how this should be implemented. Your comment in https://github.com/Shen-Language/shen-sources/pull/37 seems to contradict the description above:

`shen -l file.shen` `->` `["shen" "-l" "file.shen"]`

and

"In ports that support running scripts, the first element of the list shouldn't be the name of the interpreter executable"

Is there a standard way to pass in arguments that ports should conform to? And a standard way to pass in start-up script(s)?

**Comment by tizoc** [comment]
@rkoeninger this ticket doesn't consider scripts at all, thats why there is no consideration for adjustments in such cases.

Now, lets say your port has a `-l` flag to call `load` on a file after startup:

`shen -l file.shen` -> `["shen" "-l" "file.shen"]`

I don't think the above is useful in programs, it is just a good default to follow, works for ports that only support a REPL.

Now imagine a `-x` flag that is used to execute a script as if it were a standalone program (or just passing it as the first argument without flags). The script would not care about flags passed to the Shen interpreter/compiler, it only cares about flags passed to it as a program:

- `shen -x script.shen` -> `*argv*` -> `["script.shen"]`
- `shen script.shen` ->  `*argv*` -> `["script.shen"]`
- `shen --debug script.shen` -> `*argv*` -> `["script.shen"]`
- `shen script.shen script arguments and --flags` -> `*argv*` -> `["script.shen" "script" "arguments" "and" "--flags"]`
- `shen --debug script.shen script arguments and --flags` -> `*argv*` -> `["script.shen" "script" "arguments" "and" "--flags"]`

In the last examples the `--debug` flag is an argument for the shen interpreter/compiler, not the script, your script's argument vector starts at the script itself. This is only relevant for ports that run scripts, if you port generates executables, then this situation doesn't exist.

> Is there a standard way to pass in arguments that ports should conform to?

The only thing that is required for compatibility is that it is made accessible as a list of strings, either by setting `*argv*` or by overriding `command-line`.

> And a standard way to pass in start-up script(s)?

There is no standard way to pass start-up scripts (not yet). The nearest thing has for this is the `*hush*` global variable, that when set to true, doesn't print anything when calling a variety of functions that are used internally for reporting load times and stuff like that (like `output`).

But it doesn't really do what we would want, because `output` is still a function that you may want to use in your programs, so the work required to get this working correctly is a big more than it seemed at first.

Some of the things that need to be handled:
- Exceptions (right now those are catched by the REPL)
- What to do with partial functions (in the REPL, you get a prompt asking you if you want to track the function, that doesn't work when running scripts, it should be an error instead)
- Find all the internal functions that generate reporting by printing and make it so that they only print output when in interactive mode (this is basically `*hush*` but more specific)
- Maybe handle shebangs? (`#!/usr/bin/shen -x` as first line)
- Other stuff I may be missing

The ticket for that is #4.
