### ISSUE TITLE
Cap complexity calculation in Prolog to not overflow in 32bits systems.

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#34]
Relevant functions in `prolog.shen`:

- `head_abstraction`
- `complexity_head`
- `complexity`

**Comment by doublec** [comment]
is there a constant for max number size for a shen implementation? We could then cap complexity at that value during the calculations.

**Comment by doublec** [comment]
I've done a pull request outlining my thoughts in the previous comment. There was no need for a max number constant though. Such a thing might still be useful for other reasons.
