### ISSUE TITLE
Hooks like read-char-code but for writting chars

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#38]
The kernel provides `read-char-code`, but an analogue function for writting chares is missing.

A `(write-char-code N Stream)` function, similar to `write-byte` but that can be overriden by the port to handle non-ASCII characters would do. The `pr` function would then be changed to use this instead of `write-byte`.

**Comment by rkoeninger** [comment]
Is this necessary or likely to be included in the future given the changes in v21? I think the decision to make kernel size a priority concern precludes this.

**Comment by tizoc** [comment]
The only thing that v21 changes in regards to this is that the function would be defined inside the `shen` namespace.

But I don't know if it will be added, so far it has not been necessary (unlike `read-char-code` which was necessary to make Shen/SBCL work on Windows when using newer versions of SBCL).

If a ports happens to need be able to control how strings are written, it is probably better for the port to override `pr` instead, it is going to perform better too (being able to write all the string at once instead of doing so byte per byte).

Closing.
