### ISSUE TITLE
Feature based conditional expansion

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#41]
Macro for feature based expansion, will be useful mainly for portable libraries that need different code evaluated/compiled depending on which platform is loading it.

May be useful in the kernel too to handle optional features.

Based on Scheme's [SRFI-0](https://srfi.schemers.org/srfi-0/srfi-0.html)

```lisp
\* ports would define their own list, with one of the elements being the port name *\
(set *features* [shen-elisp feat1 feat2])

(defmacro cond-expand-macro
  [cond-expand] -> (error "Unfulfilled cond-expand.")
  [cond-expand true Body]
    -> Body
  [cond-expand [and] Body | MoreClauses]
    -> Body
  [cond-expand [and Feature | MoreFeatures] Body | MoreClauses]
    -> [cond-expand
        Feature [cond-expand [and | MoreFeatures] Body
                             | MoreClauses]
        | MoreClauses]
  [cond-expand [or] Body | MoreClauses]
    -> [cond-expand | MoreClauses]
  [cond-expand [or Feature | MoreFeatures] Body | MoreClauses]
    -> [cond-expand
        Feature Body
        true [cond-expand [or | MoreFeatures] Body | MoreClauses]]
  [cond-expand [not Feature] Body | MoreClauses]
    -> [cond-expand
        Feature [cond-expand | MoreClauses]
        true Body]
  [cond-expand Feature Body | MoreClauses]
    -> Body where (element? Feature (value *features*))
  [cond-expand Feature Body | MoreClauses]
    -> [cond-expand | MoreClauses])
```

used like this:

```lisp
(cond-expand
 feat1 (pr "has feat1c#10;") \\ prints this
 feat2 (pr "has feat2c#10;"))

(cond-expand
 no-feat (pr "has no-featc#10;")
 true (pr "doesn't have no-featc#10;")) \\ prints this

(cond-expand
 (and feat1 feat2) (pr "has feat1 and feat2c#10;") \\ prints this
 true (pr "doesn't have both feat1 and feat2c#10;"))

(cond-expand
 (or no-feat feat1 feat2) (pr "has no-feat or feat1 or feat2c#10;") \\ prints this
 true skip)

(cond-expand
 (not no-feat) (pr "doesn't have no-featc#10;") \\ prints this
 no-feat (pr "has no-featc#10;")
 true skip)

(cond-expand
 no-feat (pr "has no-featc#10;")) \\ raises error
```

It is just a first draft, it is incomplete but wanted to share to get other's thoughts on this.

**Comment by tizoc** [comment]
A slightly more advanced option that can handle both this and other uses is a version of `cond` that is evaluated at read-time and is not attached to "features" (this is what Chez Scheme calls `meta-cond`). With such construct, we would just have to agree about how to represent features across ports to get the same functionality this issue attempts to solve.

**Comment by tizoc** [comment]
Just for completeness, a `meta-cond` like version (much simpler macro):

```lisp
(defmacro cond-expand-macro
  [cond-expand] -> (error "Unfulfilled cond-expand.")
  [cond-expand Cond Body | Clauses] -> (if (eval Cond)
                                           Body
                                           [cond-expand | Clauses]))

\\ Simplistic, just to illustrate
(define feature?
  Sym -> (element? Sym (value *features*)))

(set *features* [shen-scheme])

(cond-expand
 (feature? shen-scheme) (define some-fun -> shen-scheme-specific-code)
 true (define some-fun -> generic-code))
```

Example:

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 20.0
running under Scheme, implementation: chibi-scheme
port 0.15 ported by Bruno Deferrari


(0-) (defmacro cond-expand-macro
  [cond-expand] -> (error "Unfulfilled cond-expand.")
  [cond-expand Cond Body | Clauses] -> (if (eval Cond)
                                           Body
                                           [cond-expand | Clauses]))
cond-expand-macro

(1-) (define feature?
  Sym -> (element? Sym (value *features*)))
feature?

(2-) (set *features* [shen-scheme])
[shen-scheme]

(3-) (cond-expand
 (feature? shen-scheme) (define some-fun -> shen-scheme-specific-code)
 true (define test -> generic-code))
some-fun

(4-) (some-fun)
shen-scheme-specific-code
```

**Comment by tizoc** [comment]
@rkoeninger any thoughts on this one? it would help with adding library code separately from kernel releases.

**Comment by rkoeninger** [comment]
I think something like this is vital to making the language grow beyond a curiosity. Portable filesystem and networking libraries are a must.

We just need to make sure we're all on the same page when it comes to what feature symbols are for what. My experience from Common Lisp is that each port has it's own name for each operating system, etc.

I'm thinking a port should provide a symbol for itself, its platform and maybe platform implementation:

shen-cl running in SBCL would offer `shen-cl`, `common-lisp`, `sbcl`
ShenSharp running on .NET Framework would offer `shen-sharp`, `clr`, `dotnet`

Although, the `*language*`, `*implementation*` and `*release*` variables help with that. I also make sure the `*os*` variable is always detected and set.

I was playing with Shen on JavaScript and realized we might need to provide more platform information, like whether a filesystem or console is even available (or visible as it's usually not in the browser), or if we're running in headless mode.

**Comment by tizoc** [comment]
Yes, the idea is to be able to gracefully handle differences between platforms (like the javascript example), and also to make it easier to have a bunch of semi-standard code under the `Shen-Language` org where port maintainers can help with specifics about their own ports. Such place would allow for more (and easier) experimenting of extensions than the kernel does (which ideally should be fairly stable and small).

And of course, for regular users to be able to write portable libraries.

Anyway, `cond-expand` (the general idea, details can change) is the best I can think of, it is both simple and flexible, and it is something that is already in use as a solution by implementations of a language facing a similar situation (Scheme).

**Comment by rkoeninger** [comment]
I'm not sure about the name `cond-expand`, as it's not intuitive to me what that does. Maybe something like `with-feature` or `when-feature` or `match-feature` would be better?

But my only nitpick is the naming since you seem to have this already figured out. Are you going to make a PR for it or do you want me to open one?

Also, with the addition of this feature and the requirement that ports define/amend the `*features*` variable, I think we would have reason to release this as Shen 21.

**Comment by tizoc** [comment]
`cond-expand` is just a name that already exists and which has history in Scheme from where I'm copying the idea, could be something else (I like `feature-case-expand` if I had to pick a new name).

The version provided by Chez (`meta-cond`) is more general, and can be used for everything `cond-expand` does and more. It is also less code to implement (as seen in the code blocks I wrote in the previous comments). The drawback is that for feature-based expansion the interface is not as nice, and thats why I lean towards the more restricted version.

Thoughts on that?

**Comment by rkoeninger** [comment]
The first thing the came to mind was "why not both?". `cond-expand` for any conditionals evaluate-able at read time and `feature-expand` just for feature presence (with and/or/not).

But if you want to keep it small, I'd be temped to go with `cond-expand`, the more powerful option, and then a library could introduce `feature-expand` on top of it as a convenience.

**Comment by rkoeninger** [comment]
I'm not as sure about this as I apparently was a couple years ago. This feature is as relevant as Shen is a general-purpose language. Is it a language for writing complete applications, which might result on depending on platform-specific features? I don't even think it should have I/O.

**Comment by tizoc** [comment]
It is very useful in itself, like conditional expansion in C using the preprocessor. But it is also quite necessary if one wants to be able to write portable code in Shen that depends on platform-specific functionality. Some platforms may provide the same functionality through different names or apis, or some may offer efficient ways to do things that the others don't, and in those cases you would have to fallback to a portable less-efficient way of doing something.

A basic example:

```shen
\\ Here cond-expand is inside the function, but could just wrap
\\ the whole definition instead
(define exit-program
  ExitCode -> (cond-expand
                (= (language) "Common Lisp") (cl.exit ExitCode)
                (= (language) "Scheme") (scm.exit ExitCode)
                true (error "exit not supported")))
```

Then Shen/CL will end up compling this:

```shen
(define exit-program
  ExitCode -> (cl.exit ExitCode))
```

and Shen/Scheme this:

```shen
(define exit-program
  ExitCode -> (scm.exit ExitCode))
```

**Comment by tizoc** [comment]
@rkoeninger the Shen/CL port uses the Common Lisp version of this a lot btw (conditional expansion through `#+`)

**Comment by tizoc** [comment]
I like the version I wrote originally on the first post of this thread better for what needs to be solved btw, will change the PR to that and call it `feature-expand`.

**Comment by rkoeninger** [comment]
I get how the feature works, I'm questioning the direction this would take things in. I'm looking at the [downloads section](https://shen-language.github.io/#downloads) on the open source site and worrying that we'll have compatibility tables for each of these optional APIs.

**Comment by tizoc** [comment]
@rkoeninger the person who needs to know is the library/program author trying to write code portable across multiple ports. If I'm trying to write a program that uses `exit` which I want to run on Shen/CL and Shen/Scheme I already know they provide a function to exist the program, just with different names. Through conditional expansion I can decide what to expand to at read-time and share the code. Same for code that has to change depending on the operating system.

What do you see as different here when compared to C's `#ifdef`, Common Lisp feature flags or Scheme's SRFI-0 ? It is solving the same problem, with the same approach (conditional expansion at compile-time by checking flags).

**Comment by tizoc** [comment]
Btw, don't put much weight on discussions from years ago, things were different back then, the intention was to grow the kernel, but now I want to avoid touching it unless there are bugs or performance can be improved. Other than for keeping compatibility, If Mark decides to share his latest changes to the SP Kernel and things have changed too much in the BSD one, integration is going to be very difficult. Changes/extensions done "from the outside" are much safer.

The IO functions are part of the spec, cannot be removed without breaking that. Platforms that cannot provide such functionality can still add stubs (in web-browser-JS for example, `open` can return an object on which `close` and `write-byte` do nothing, and `read-byte` always returns 0).
But in any case, that is a whole different discussion.

**Comment by rkoeninger** [comment]
This thread is kind of all over the place, before we wanted to extend the kernel, now I agree with Mark on keeping the kernel small, but also disagree with Mark that the language should be kept stable because I think the kernel should be even smaller (no I/O other than maybe logging).

I'm thinking of Shen as a multi-platform library that would get embedded in other applications. One of those applications could be a command-line repl. (remove `shen.shen` from the kernel) Do we need repls in 20 different languages?

The best way to have portable Shen is to have Shen be a thing that is universal across all platforms in the first place. `exit` wouldn't be a thing that a Shen program does with this mentality.

Just some thoughts I wanted to express.
