### ISSUE TITLE
Fix `nth`

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#53]
[Just so that I don't forget before v21]

`nth` fails horribly when the element is not on the list, or the index is not an integer, update its definition to solve that problem:

```
(define nth 
  1 [X | _] -> X
  N [_ | Y] -> (nth (- N 1) Y)
  N X -> (error "nth applied to ~A, ~A~%" N X))
```

**Comment by rkoeninger** [comment]
@tizoc was this addressed in the 21 release?
