### ISSUE TITLE
Add `,` (comma) to the list of external symbols.

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#54]
This fixes a bug that Willi was experiencing in Shen/Scheme but not in Shen-Professional. Mark looked into it and said the reason was that in Shen-Professional `,` is an external because it is a symbol that is part of the sequent notation. The BSD Kernel is missing this, add before releasing v21.

**Comment by rkoeninger** [comment]
@tizoc was this addressed in the 21 release?

**Comment by tizoc** [comment]
@rkoeninger yes, sorry, forgot to close this and #53.
