### ISSUE TITLE
Add Unicode support

### ISSUE THREAD

**Issue by zaoqi** [Shen-Language/shen-sources#55]

**Comment by rkoeninger** [comment]
@zaoqi Unicode is supported on a port-by-port basis. The current design premise for the kernel is to keep it as small as possible, so this is not likely to become a Shen standard feature.

You'll have to try different ports and see if any support what you're looking for, but you're not likely to find support beyond UTF-8 as I/O in Shen is byte-oriented.

**Comment by tizoc** [comment]
As @rkoeninger noted, if you are going to work with Unicode, what you probably want is to leverage what the underlying platform provides.

A pure-Shen implementation is possible, but if it happens, it is going to be in a library, and not as part of the Kernel.

**Comment by zaoqi** [comment]
So I will implement a Lisp like Shen

**Comment by tizoc** [comment]
I don't know what is it that you need exactly ("unicode support" is too general and can mean many different things), but:

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 20.1
running under Common Lisp, implementation: SBCL
port 2.2 ported by Mark Tarver


(0-) "神"
"神"

(1-) (pr "神")
神"神"

(2-) (pos "神" 0)
"神"

(3-) (string->n "神")
31070

(4-) (n->string 31070)
"神"
```

**Comment by zaoqi** [comment]
```
$ shen

Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, version 20.0
running under Haskell 2010, implementation: GHC 8.0.1
port 0.3.2 ported by Mark Thom


(0-) a
a

(1-) 神
n->string: needs an ASCII code point
```

**Comment by zaoqi** [comment]
```

(1-) (load "a")
a: openBinaryFile: does not exist (No such file or directory)

(2-) (load "神")
n->string: needs an ASCII code point

```

**Comment by rkoeninger** [comment]
shen-sbcl inherits [unicode support from SBCL](https://www.cliki.net/Unicode%20support). Also remember [it uses `read-char-code`](https://github.com/Shen-Language/shen-cl/blob/master/src/overwrite.lsp#L122), which is only for shen-ccl and shen-sbcl. Does shen-clisp handle it?

Shentong uses [Data.Text](https://hackage.haskell.org/package/text-1.2.3.0/docs/Data-Text.html), which should support unicode, but it might be doing [byte-by-byte I/O](https://github.com/mthom/shentong-core/blob/0f96b9af51224a32f191d6b6bac5a1691fec54b0/Primitives.hs#L295) which breaks multi-byte codepoints.

**Comment by tizoc** [comment]
It is very hard to help @zaoqi without knowing what his actuals needs are, and he is being very cryptic about it.

@zaoqi we may be able to help you (or at least point you where to look) if you are more specific about what requirements you have, like for example, if running the Haskell port is a requirement, or any port will do. Also what your actual unicode needs are, just being able to read and print strings with unicode characters is enough? (plus loading files with unicode characters in their filenames).

**Comment by zaoqi** [comment]
```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 19.2
running under Javascript, implementation: generic
port 3.0.0 ported by Ramil Farkhshatov


(0-) "神"
"神"

(1-) a
a

(2-) 神

```
I need shen-js or any port support Unicode Symbol.

**Comment by tizoc** [comment]
Oh I see. That one is quite a bit more complicated, because the Shen grammar doesn't accept non-ascii characters, and thats not likely to change in the near future.

But for your own program, you can patch the grammar at runtime to make that specific case work:

```
(define shen.symbol-code?
  N -> (or (= N 126)
           (and (> N 94) (< N 123))
           (and (> N 59) (< N 91))
           (and (> N 41) (< N 58) (not (= N 44)))
           (and (> N 34) (< N 40))
           (= N 33)
           (= N 31070)))
```

I added `(= N 31070)`, that makes `31070` (the numeric code for `神 `) a valid symbol character in the grammar.

```
Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 19.2
running under Javascript, implementation: generic
port 3.0.0 ported by Ramil Farkhshatov

(0-) (intern "神")
神

(1-) (pos "神" 0)
"神"

(2-) (string->n "神")
31070

(3-) (define shen.symbol-code?
  N -> (or (= N 126)
           (and (> N 94) (< N 123))
           (and (> N 59) (< N 91))
           (and (> N 41) (< N 58) (not (= N 44)))
           (and (> N 34) (< N 40))
           (= N 33)
           (= N 31070)))
shen.symbol-code?

(4-) 神
神

(5-) (define 神 -> shen)
神

(6-) (神)
shen
```

Hope this helps.

**Comment by zaoqi** [comment]
Chinese characters can be used as lowercase like Haskell,Go
