### ISSUE TITLE
Standard error stream (STDERR)

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#6]
# Standard error stream discussion

Right now Shen has no concept of standard error stream, only standard input. Adding this is easy, but ports will have to update accordingly.
## Current implementations
- https://github.com/tizoc/shen-scheme#standard-error-stream

_TODO: add others_
## Proposal

Add a new `*sterror*` global variable that ports have to point to the standard error stream on init (just like they do with `*stinput*` and `*stoutput*`).

Also a `(sterror)` function that returns the value in this variable (just like the `stinput` and `stoutput` functions are implemented now). This would be added to the kernel, no need for ports to implement it.

**Extra**: a function analogous to the regular print but that sends the output to `*sterror*`. Name for this?
## Notes

May not make sense for all ports. Make `*sterror*` an alias of `*stoutput*` by default for such cases?

**Comment by tizoc** [comment]
@gravicappa stderr issue here.

**Comment by deech** [comment]
Why provide this in the kernel? How would this apply to the JS port, for example?

**Comment by tizoc** [comment]
@deech the ports still have to make stderr available, so a library is not enough. Lets say nothing changes in the kernel (adding a `(sterror)` function is the only change required), port maintainers still have to agree on a common way to access stderr.

JS when running in node (or similar environments) has stderr, in the browser it has the same problem as stdout and stdin (not sure what the JS port does in that case), but lets say stdout uses `console.log` then stderr could be `console.warn` or `console.error` (if not an alias of stdout like I mentioned in the note).

**Comment by deech** [comment]
@tizoc Ok, I see the logic there, but it still seems as though devs in environments without concepts of `std{in,out,err}` are being forced to deal with them. Maybe make `(sterror)` completely optional?

I am, in fact, not completely comfortable with `*stinput*` being part of the standard either. For example, say I want to port Shen to pure SQL which does not specify these things I have to hack around it. In general I think Shen has a strong use-case not just as a full-blown language but as an embedded type system/Prolog. Making the standard command line IO part of the standard makes this harder to achieve.

**Comment by gravicappa** [comment]
@deech, the kernel does error reporting. I don't know a way to redirect it to `sterror` with a library.

**Comment by tizoc** [comment]
@deech some options for the port maintainer in such cases are:

- throw an error when those ports are accessed
- silently drop whatever is sent there
- make stderr an alias to stdout

SQL is kinda a corner case, I wouldn't sacrifice what should be normal because of a possible SQL port, but at the same time, there is no reason why we can't define things to accommodate such cases.

**Comment by tizoc** [comment]
The minimum needed for this was pushed in https://github.com/tizoc/shen-sources/commit/f6a4441966e376edadc16ddb3852fb28bb6f3d0e

If the port doesn't set `*sterror*`, then it will just be an alias to `*stoutput*`.
