### ISSUE TITLE
type-theory identifiers and packages

### ISSUE THREAD

**Issue by NHALX** [Shen-Language/shen-sources#62]
The package prefix is being prepended to 'type#', instead of the identifier, which breaks things like 'preclude'.

Shen/PRO has the same problem.

```
(0-) (package test []
 (datatype something
    ______________________
           axiom;))
test.type#something

(1-) (preclude [test.something])
[test.type#something]

(2-) (preclude [test.type#something])
[test.type#something]

(3-) (datatype other ___ axiom2;)
type#other

(4-) (preclude [other])
[test.type#something]

```

**Comment by tizoc** [comment]
@NHALX does this happen in SP? if no, what is the name of the resulting defun for the type?

**Comment by NHALX** [comment]
@tizoc It is the same in Shen-pro 23.5: test.type#something.

24 is supposed to have a lot of changes, but I haven't heard anything about this being one of them. 

The current package system sucks for a variety of reasons, I should start compiling a list of grievances against it.

**Comment by tizoc** [comment]
Ok, thank you. I think changing `intern-type` to append "#type" to the name is a good solution for now (cc: @rkoeninger )

**Comment by rkoeninger** [comment]
Does this work?

```shen
(0-) (package test []  (datatype something     ______________________            axiom;))
test.something#type
```

I got tripped up not realizing if I wrote `#type` as an idle symbol, the package macro would throw `shen.` on there.
