### ISSUE TITLE
Prolog: cut causes failures when it shouldn't

### ISSUE THREAD

**Issue by NHALX** [Shen-Language/shen-sources#63]
I think maybe a continuation isn't being constructed properly when the cut is introduced. The test below succeeds in both cases, as shown by the call to trace, but fails for some reason when the result isn't wrapped in an arbitrary list. 

Shen/PRO has the same problem.
  
```
(0-) (defprolog testB
  X <-- (when false) ! (when false);
  X <-- (unify X 1); )
testB

(1-)
(defprolog prolog.trace
  Msg X <-- (when (do (output "~A: ~R~%" Msg X) true)); )
prolog.trace

(2-)
(prolog? (testB A)
         (prolog.trace "1" A)
         (return [A]))
1: 1
[1]

(3-)
(prolog? (testB A)
         (prolog.trace "2" A)
         (return A))
2: 1
false
```

**Comment by NHALX** [comment]
This is a better minimal example of failure:

```
(defprolog broken
  X X <-- !;)

(prolog? (is X 1)
         (broken X Z)
         (return Z))

```
The problem is in these shen functions:

```
(define catchpoint
  -> (set *catch* (+ 1 (value *catch*))))

(define cutpoint
  Catch Catch -> false
  _ X -> X)
```

Because at the entry of 'broken' (shen.cutpoint Throwcontrol ...) is called. (value *catch*) starts off at 0 so the catchpoint value is 1 and the function also returns 1 so 'cutpoint' has it's first clause matching, signaling failure.

Catchpoint values need to be tagged with a unique value to disambiguate it from results.

**Comment by NHALX** [comment]
I suppose this is good enough:

```
(set shen.*catchpoint-tag* (gensym catchpoint))

(define shen.catchpoint
    -> (let Index (+ 1 (value shen.*catch*))
          (do (set shen.*catch* Index)
              [(value shen.*catchpoint-tag*) Index])))
```

**Comment by tizoc** [comment]
Sorry for letting hang so long, completely forgot about it.

Your analysis is correct and your fix too. The only thing I don't like is that it requires a new allocation but I cannot think of a better alternative.
