### ISSUE TITLE
Comments are executed as valid code

### ISSUE THREAD

**Issue by vrescobar** [Shen-Language/shen-sources#73]
I create a file, named `test1.shen`

```lisp
// (print "Single comment should be ignored")
/*
    (print 
        "Multiline comment should also be ignored")
    To load a file from shen-sblc command line I can use
    shen-sblc -e '(load "test1.shen")'
*/

(+ 1 1)
```
And then I executed it ending up in an infinite loop because all code commented was executed as if it wasn't commented. Including the `load`.

I tried it with shen-c and with shen-sblc (based on Shen 21, port 2.2 ), both implementations behave identical so I guess the parsing issue must be at shen's kernel.

**Comment by tizoc** [comment]
Hello @vrescobar, comments in Shen use backward slashes, see: http://shenlanguage.org/shendoc.htm#Comments

**Comment by vrescobar** [comment]
Oops, thank you for the correction. I realize now that somehow these lines are interpreted as top level symbol and the inner expressions evaluated.

I guess I should check why the vscode shen plugin which creates such comments with the comment-code hot key.

**Comment by tizoc** [comment]
@vrescobar oops, my bad, just saw why. Will publish an updated version of the vscode extension soon (once I figure out why the publish command is failing)

**Comment by tizoc** [comment]
Done.
