### ISSUE TITLE
make fetch is broken in head as binary for v2.5.0 has not been released

### ISSUE THREAD

**Issue by vrescobar** [Shen-Language/shen-sources#76]
Apparently the last release the bootstraped sblc version for the 2.4.0 has not been made public but it is already part of the Makefile at head. 

```
make fetch
wget https://github.com/Shen-Language/shen-cl/releases/download/v2.4.0/shen-cl-v2.4.0-macos-prebuilt.tar.gz
--2019-08-30 22:00:19--  https://github.com/Shen-Language/shen-cl/releases/download/v2.4.0/shen-cl-v2.4.0-macos-prebuilt.tar.gz
Auflösen des Hostnamens github.com (github.com)… 140.82.118.4
Verbindungsaufbau zu github.com (github.com)|140.82.118.4|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2019-08-30 22:00:20 FEHLER 404: Not Found.
```

**Comment by vrescobar** [comment]
**Workaround** In case someone wants to  build the sources from master/HEAD it is possible to do it with a previous shen-sblc version installed at the system, just patch the Makefile and run the instructions omitting the tag version and the fetch steps.

```
diff --git a/Makefile b/Makefile
index 84adfaa..5348fa6 100644
--- a/Makefile
+++ b/Makefile
@@ -45,7 +45,7 @@ ShenClArchiveName=$(ShenClFolderName)$(ArchiveSuffix)
 ShenClArchiveUrl=$(UrlRoot)/$(ShenClTag)/$(ShenClArchiveName)
 
 ifndef Shen
-       Shen=.$(Slash)shen-cl$(Slash)shen$(BinarySuffix)
+       Shen=/usr/local/bin/shen-sbcl
 endif
 
 ReleaseFolderName=ShenOSKernel-$(GitVersion)
```

Just execute:
```
make pure
make klambda
make release
```

**Comment by rkoeninger** [comment]
Sorry, I don't have a mac so only the windows version is pre-built. I usually pre-built a linux version in ubuntu too but must have forgot for 2.4 and 2.5. Also, 2.5.0 is the most recent release for shen-cl.

Does `make klambda Shen="/path/to/shen"` not work?

**Comment by vrescobar** [comment]
hi Robert,

yes I can manually switch the shen path and just skip that fetch, but also the klambda sources are not available as tar.gz in the releases (originally just wanted to download them to update the ShenScript kernel at the other repo).

I ignore whether sbcl can generate binaries for other platforms, but since I have a mac I could manually provide some compiled binaries if necessary.

**Comment by rkoeninger** [comment]
every release since 20.0 has had pre-rendered klambda in the release in a zip and a tar.gz. The tar.gz for 21.1 can be downloaded [here](https://github.com/Shen-Language/shen-sources/releases/download/shen-21.1/ShenOSKernel-21.1.tar.gz).

Made an issue on shen-cl about the missing macOS builds: https://github.com/Shen-Language/shen-cl/issues/29

**Comment by vrescobar** [comment]
sbcl prebuilds for macos are already available (see the other issue). Perhaps it makes sense to have a common CI for all projects so the releases of this project are also automatically updated:

https://github.com/Shen-Language/shen-sources/releases

The makefile in this project still fails to fetch a binary, I should check later which is the URL used for sbcl.

**Comment by rkoeninger** [comment]
@vrescobar I updated the makefile to fetch shen-cl v2.6.0 - there are prebuilds uploaded for all three major platforms for that version

**Comment by vrescobar** [comment]
The compilation works good so I will close the issue, but I have a question:

```

Shen, copyright (C) 2010-2015 Mark Tarver
www.shenlanguage.org, Shen 21.1
running under Common Lisp, implementation: SBCL
port 2.6 ported by Mark Tarver
exit REPL with (cl.exit)

(0-)
```

Why it does still say that the sources are 21.1? 
is it just because at ./sources/declarations.shen line 85 it is not updated or there is a different version between the soruces, the SP builds, and the ports? 


I compiled at master's head btw.

**Comment by rkoeninger** [comment]
@vrescobar It's "./sources/declarations.shen line 85" as you say. The version just hasn't been bumped since the 21.1 release of the kernel.

**Comment by tizoc** [comment]
@vrescobar 21.1 is the version of the open source Shen Kernel, 2.6 is the version of the Common Lisp port. Shen Professional has it's own version (24). Mark maintained the open source kernel until version 19, then went on to work on Shen Professional.
