### ISSUE TITLE
cond form / building code with goto-like syntax

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-sources#82]
What potential issues would there be with having the kernel replace `cond` forms with `if` chains?

Every non-lisp port I've worked on has had to write out the code to handle `cond`, invariably producing an `if`-`else` chain. Would be simpler if the kernel handled it, and it could standardize no-clause-matched behavior. And do a couple of expression simplifications:

```shen
[[true  Consequent] | _]       -> Consequent
[[false _]          | Clauses] -> (build-cond Clauses)
```

I don't think this would require a spec change as `cond` could still be part of the spec, but a port just won't encounter it if using a newer version of the kernel and can leave out code to handle it.

---

Also, I wonder if we can handle other things this way too. The kernel can start offering functionality without breaking ports and ports can just phase out code over time. And new ports won't have to implement that functionality in the first place.

**Comment by tizoc** [comment]
@rkoeninger found it: https://groups.google.com/forum/#!topic/qilang/fZv7O0RallA and https://github.com/Shen-Language/shen-sources/issues/39#issuecomment-349040829

This is doable in a portable way, and many ports could benefit from it (in particular, the ones that implement an interpreter instead of translating kl into another language). Same as some of the transformations Shen/Scheme does. Will open an issue so that I don't forget.

**Comment by rkoeninger** [comment]
> Having the compiler generate `cond` clauses for pattern matching is very useful to identify pattern matching on functions to implement a pattern matching factorization optimization (not just identifying it, the organization makes it much easier too).

Does Shen/Scheme do this? I haven't seen any port do that before. I was looking at doing this when generating F# (since F# has pattern matching). But the hard part wasn't identifying an if-else chain, it was identifying patterns and undoing the `reduce` process.

(replacing bindings with accessor expressions is what's happening here right?)

https://github.com/Shen-Language/shen-sources/blob/8bcc8abb4d1d97af956c5f93ccf7eb5b73e05bc6/sources/core.shen#L315-L343

**Comment by tizoc** [comment]
It doesn't yet, but will soon. A very similar transformation works for Shen/CL too. Once I get it working on Shen/Scheme I will adapt it to Shen/CL. Without a construct that works like a GOTO this optimization is not very doable (when translating code to another language, ports that implement interpreters may still benefit from it), but Common Lisp has a GOTO-like construct. Shen/Scheme doesn't, but if Scheme code is generated in a very specific ways, it seems Chez is able to optimize it very well.

The snippet you link does another thing, it avoids having to reconstruct a value that was deconstructed. For example (stupid code, but good enough to show the optimization):

```shen
(define without-trailing-as
  "" -> ""
  (@s First Rest) -> (if (= First "a")
                         (without-trailing-as Rest) 
                         (@s First Rest)))
```

gets compiled into the following klambda:

```shen
(defun without-trailing-as (V1196)
 (cond ((= "" V1196) "")
        ((shen.+string? V1196)
         (if (= (pos V1196 0) "a") 
                (without-trailing-as (tlstr V1196)) 
                V1196))
        (true (shen.f_error without-trailing-as))))
```

Note how in the `else` branch of the `if` it doesn't reconstruct the string but instead reuses the original reference to the value (variable `V1196`). It also avoids the potentially-expensive call to `tlstr` unnecessarily when the value will not be used.

I think this transformation is buggy in some cases (like when working with mutable vectors), but I had a long exchange with Mark about this and concluded that it should be left as is. What he said is that `@v` and mutation should not be combined, so the behavior in such cases is undefined as far as Shen cares. Another issue is that if the tail of the string/vector is referenced multiple times, all those get replaced by calls to `tlstr`, but factorization solves this too.

On another topic, but kinda related: now that there are precompiled binaries for all common platforms, is it still a good idea for Shen/CL to be all written in Common Lisp? Parts like the compiler are much easier to work with when the code is Shen (for example, to implement optimizations like this one).

**Comment by rkoeninger** [comment]
A `goto`-like construct would allow the code to jump out of a consequent branch and continue checking conditions in a `cond`-like construct, but why is that needed? What would a Shen pattern match in generated CL, Scheme or JS look like when making use of `tagbody` or `switch`/`break`?

**Comment by tizoc** [comment]
See this code:

```scheme
  (define (kl:s V1263 V1264 V1265)
    (begin
      (define (Jump1268 V1265 V1263 V1264)
        (cons V1263 (cons V1264 (cons V1265 '()))))
      (define (Jump1275 V1263 V1264 V1265)
        (if (pair? V1265)
            (let ([Tl1274 (cdr V1265)])
              (if (eq? '* (car V1265))
                  (if (pair? Tl1274)
                      (let ([Tl1272 (cdr Tl1274)])
                        (if (pair? Tl1272)
                            (if (null? (cdr Tl1272))
                                (kl:simplify
                                  (cons
                                    '*
                                    (cons
                                      (cons
                                        '*
                                        (cons
                                          V1264
                                          (cons (car Tl1274) '())))
                                      Tl1272)))
                                (Jump1268 V1265 V1263 V1264))
                            (Jump1268 V1265 V1263 V1264)))
                      (Jump1268 V1265 V1263 V1264))
                  (Jump1268 V1265 V1263 V1264)))
            (Jump1268 V1265 V1263 V1264)))
      (define (Jump1276 V1263 V1265 V1264)
        (if (kl:= 1 V1264) V1265 (Jump1275 V1263 V1264 V1265)))
      (define (Jump1277 V1263 V1264 V1265)
        (if (kl:= 1 V1265) V1264 (Jump1276 V1263 V1265 V1264)))
      (define (Jump1278 V1264 V1263 V1265)
        (if (kl:= 0 V1265) 0 (Jump1277 V1263 V1264 V1265)))
      (define (Jump1279 V1265 V1263 V1264)
        (if (kl:= 0 V1264) 0 (Jump1278 V1264 V1263 V1265)))
      (define (Jump1280 V1264 V1263 V1265)
        (if (eq? '* V1263)
            (if (number? V1264)
                (if (number? V1265)
                    (* V1264 V1265)
                    (Jump1279 V1265 V1263 V1264))
                (Jump1279 V1265 V1263 V1264))
            (Jump1268 V1265 V1263 V1264)))
      (define (Jump1287 V1263 V1264 V1265)
        (if (pair? V1265)
            (let ([Tl1286 (cdr V1265)])
              (if (eq? '+ (car V1265))
                  (if (pair? Tl1286)
                      (let ([Tl1284 (cdr Tl1286)])
                        (if (pair? Tl1284)
                            (if (null? (cdr Tl1284))
                                (kl:simplify
                                  (cons
                                    '+
                                    (cons
                                      (cons
                                        '+
                                        (cons
                                          V1264
                                          (cons (car Tl1286) '())))
                                      Tl1284)))
                                (Jump1280 V1264 V1263 V1265))
                            (Jump1280 V1264 V1263 V1265)))
                      (Jump1280 V1264 V1263 V1265))
                  (Jump1280 V1264 V1263 V1265)))
            (Jump1280 V1264 V1263 V1265)))
      (define (Jump1288 V1263 V1264 V1265)
        (if (kl:= 0 V1265) V1264 (Jump1287 V1263 V1264 V1265)))
      (define (Jump1289 V1263 V1265 V1264)
        (if (kl:= 0 V1264) V1265 (Jump1288 V1263 V1264 V1265)))
      (if (eq? '+ V1263)
          (if (number? V1264)
              (if (number? V1265)
                  (+ V1264 V1265)
                  (Jump1289 V1263 V1265 V1264))
              (Jump1289 V1263 V1265 V1264))
          (Jump1280 V1264 V1263 V1265))))
```

It is the result of compiling the following function in Shen/Scheme with the pattern factorization optimization applied:

```shen
(define s
  + M N -> (+ M N)      where (and (number? M) (number? N))
  + 0 F -> F
  + F 0 -> F
  + A [+ B C] -> (simplify [+ [+ A B] C])
  * M N -> (* M N)    where (and (number? M) (number? N))
  * 0 F -> 0
  * F 0 -> 0
  * F 1 -> F
  * 1 F -> F
  * A [* B C] -> (simplify [* [* A B] C])
  Op A B -> [Op A B])
```

What it does is to convert the `cond` to a tree of `if`s, merging the predicates that are repeated multiple times in the `cond` so that each predicate doesn't have to be made more than once. Without GOTO, you get a lot of code duplication in the elses, so you end producing much more code. With GOTO you put the repeated code in a label, and on the else branches you just jump to that code.

In the compiled code example above, each `Jump*` function represents a label and each `(Jump* ...vars)` call a GOTO to that label. This works fine in Chez because if a function is internal, and every references it access is an argument. Because nothing from the outer scope is referenced, Chez can compile it into a direct jump and avoid all the overhead, making it a construct somewhat equivalent to a GOTO.

Once I cleanup the code and commit it to Shen/Scheme it will be easier to understand.

**Comment by tizoc** [comment]
@rkoeninger the CL version of the generated code would look like the one in this article: https://web.archive.org/web/20110723182559/http://www.lambdassociates.org/Studies/study10.htm

**Comment by rkoeninger** [comment]
Point taken on the GOTO approach. I wanted to stick to function, expression-oriented code but that's not always optimal. One would have to use lazy thunks or have each case return an optional value so it can return from nested conditionals (nested under the common condition). But both these approaches would add more overhead than they would save.

I was going to close this issue. It could still be linked from the optimizations section of the porting document and/or have relevant suggested copied there.

**Comment by tizoc** [comment]
The generated code has been improved a little since I made my last comment, see: https://gist.github.com/tizoc/7076846b7e727fb2a534733ee26e8bbe

Implementation, which I think serves as a decent reference: https://github.com/tizoc/shen-scheme/blob/master/src/factorize-patterns.shen

That code is not generic, but I think a generic version may be doable without complicating it too much. `scm.goto-label` would just be `goto-label`, and ports would have to work with the code as it is during the phase before `hoist-labels`, which is a very Chez-specific transformation (takes care of converting the labels to Scheme `define`s and adding all the required parameters)

**Comment by tizoc** [comment]
Re: closing the issue, yes, this is not something that will change, at least not for now.

**Comment by tizoc** [comment]
> That code is not generic, but I think a generic version may be doable without complicating it too much.

Going to look into this after making it work for Shen/CL, if I can make a generic version then it will become a new extension available to ports.
