### ISSUE TITLE
Extension to perform transformation of dynamic code in the kernel files into a static version.

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#83]
Both `types.shen` and `declarations.shen` require calls to `eval-kl`, this forces ports to perform klambda code evaluation at startup, which in some cases can be quite costly (ports that implement an interpreter instead of translating the code to the platform's language, or ports where `eval-kl` is slow).

In `declarations.shen`, the dynamic evaluation happens [here](https://github.com/Shen-Language/shen-sources/blob/4b4c85c8f92a6dda29de0b695de4dc59140b73a8/sources/declarations.shen#L184-L213)

It constructs lambdas dynamically using `eval-kl`, the needed transformation is to just pre-evaluate the `mapcan` expression and replace it with the resulting pairs of `(cons function-name-symbol (lambda ....))`.

In `types.shen` the dynamic evaluation happens every time [declare](https://github.com/Shen-Language/shen-sources/blob/4b4c85c8f92a6dda29de0b695de4dc59140b73a8/sources/types.shen#L34-L47) is called. The transformation would be the same, pre-evaluate it and replace the calls to `declare` with the result (the function definition of the `type-signature-of-*` functions, the registration of their lambda forms, and recording in`(cons function-name type-signature-expression)` on `shen.*signedfuncs*`).

Shen/JVM includes these transformations (but made by hand):

- https://github.com/otabat/shen-jvm/blob/master/shen/src/kl-replace/types-replace.kl
- https://github.com/otabat/shen-jvm/blob/master/shen/src/kl-replace/declarations-replace.kl

Doing so [improved startup times on android immensely](https://groups.google.com/d/msg/qilang/fZv7O0RallA/U36XWS-TBQAJ).

**Comment by tizoc** [comment]
@otabat if I include this, would this help with keeping Shen/JVM and Shen/C up to date? you would not have to perform such transformations by hand anymore. Is there anything else you have had to do to get acceptable performance that has potential to be automated?

**Comment by rkoeninger** [comment]
Does this necessarily need to be an extension, or is it a transformation that make.shen could perform? Is the intention to improve performance at startup or improve performance generally?

**Comment by tizoc** [comment]
It is going to be an extension because it is a piece of generic code that is useful outside of the kernel too. But the idea is for `make.shen` to use that by default unless I find a good reason not to.

It is about improving startup time by precompiling some stuff so that it doesn't have to be evaluated at runtime.

**Comment by rkoeninger** [comment]
I always thought the rendered KL version of the kernel should be doing as little work as possible on startup, really just declaring `defun`s (initializing global functions) and a bunch of toplevel `set`s (initializing global symbols).

In ShenSharp, I actually have it evaluate the kernel starting with a primitive environment and then generate F# code that re-creates the resulting environment:

https://github.com/rkoeninger/ShenSharp/blob/b57cfb9797d038c06de41b1d54009f0fee561979/Kl.Make/Loader.fs#L73-L75

Shen/CL effectively does this by generating an executable based on the environment state after loading the kernel.

The closer `make.shen` comes to providing this to all ports by default, the better. It would even help with CL when it's a source-form library.

**Comment by tizoc** [comment]
Yes, I have to do some translation in Shen/Scheme too: everything that is not a defun gets collected and put inside an initialization function that I call during startup. Doing so will not be needed anymore once the extension goes in and `make.shen` handles this.

**Comment by tizoc** [comment]
Started doing some testing on this.

Just taking care of pre-compiling `declare`s brings down Shen/Scheme's startup time down from 0.35s to 0.25s on my computer, and Shen/Scheme's eval is probably one of the fastests.

**Comment by rkoeninger** [comment]
I've observed that in the past. In ShenSharp, it shows the loading of each form during the build and you can see it fly through almost everything and then most at a relative crawl through the top-level `declare`s.

I'm going to take a shot at a first draft of this precompiler, first focusing on `declare` elimination`. PR coming soon.

**Comment by tizoc** [comment]
@rkoeninger that part is what I'm working on 👀

The other thing that is needed is pre-compiling the lambda forms generated in `declarations.shen` to avoid the calls to `eval-kl`

**Comment by tizoc** [comment]
This is the whole thing btw:

```shen
(define undynamize
  [] -> []
  [[declare Name Sig] | Exps] -> (append (expand-declare [declare Name Sig]) (undynamize Exps))
  [Exp | Exps] -> [Exp | (undynamize Exps)])

(define expand-declare
  [declare Name Sig] -> (let Eval (eval-kl [declare Name Sig])
                             Record [set shen.*signedfuncs* [cons [cons Name Sig] [value shen.*signedfuncs*]]]
                             F* (concat shen.type-signature-of- Name)
                             KlDef (ps F*)
                             RegisterLambda [shen.set-lambda-form-entry [cons F* (shen.lambda-form F* 3)]]
                          [KlDef Record RegisterLambda]))
```

Doesn't handle the collection of all non-defun expressions happening at top-level to put them in a single initialization function, but thats going to be a separate pass (I will just use the code in Shen/Scheme that already does that)

**Comment by rkoeninger** [comment]
I started writing something like this

```shen
[defun (concat shen.type-signature-of- Name) [GoalName ProcName ContName]
  (let-macro
    (append [let]
            (mapcan (/. P [P [shen.newpv ProcName]]) TypeParams)
            [[do [shen.incinfs] [unify! GoalName Type ProcName ContName]]]))]
```

Reusing the code with `ps` is a good idea.

If you took the current `shen.exe` and used it and the `ps` to generate the next version of `shen.exe`, will `ps` have code for the `type-signature-of-` functions in that next generation of `shen.exe`?

**Comment by tizoc** [comment]
@rkoeninger no, thats why I `eval` the `declare` expression. It is the only way I feel safe about the expanded code being what it should be (since `declare` has side effects on the compiling environment, each declare will have an effect on what happens next).

**Comment by tizoc** [comment]
Btw, I'm expanding the lambdas, will submit a PR soon for you to check out and also test on your ports.

**Comment by tizoc** [comment]
Soved by #85
