### ISSUE TITLE
Release 21.2 ?

### ISSUE THREAD

**Issue by rkoeninger** [Shen-Language/shen-sources#84]
@tizoc Is a release of current changes in order? I think there should be a minor release before we start merging those extensions PRs.

PS: The real reason I'm askking is my ShenScript CI build fails without the unreleased change to `tests.shen`.

**Comment by tizoc** [comment]
@rkoeninger I think it is safe to make a new release from what is in master right now (I also just checked and see there are a few unreleased fixes). Will double-check in a bit and push a new tag+release.

**Comment by tizoc** [comment]
@rkoeninger Done.

I have to look into adding travis to this repo and automate the build of the release tarball and zip. I almost published files with some stuff inside `doc/` that shouldn't be part of the release.

**Comment by rkoeninger** [comment]
@tizoc Awesome, thanks!
