### ISSUE TITLE
Benchmark suite

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-sources#91]
The time it takes for a port to finish the test suite gives one a rough idea of it's performance, but having a suite of synthetic benchmarks would give a better idea of what is fast and what is slow, which is useful for evaluation purposes and for figuring out what needs optimization.

Another problem with using the test suite times is that the time the compiler spends producing code is also accounted for, but real programs don't spend time on the compiler (for example, the new Shen/CL compiler produces code that performs better than the old one, but the compiler itself is slower, so all the speedups don't reflect on the time it takes to run the test suite).

**Comment by rkoeninger** [comment]
Agreed that normal programs would spend a tiny fraction of their run time building code but also think that startup time and compiler performance should be some of the benchmarks that are tested.

What other specific performance issues do we want to test?

- Startup time
- Build time (code of various complexity)
- Recursive functions
- Mutually recursive function
- ?

I don't know if something like "type checking" is a benchmark as having slow type checking doesn't tell the implementer what is slow about their port.

**Comment by tizoc** [comment]
> Things like "symbol/function lookups" and "tail-recursion" would be things the port dev could do something about.

Yes, that is the kind of numbers I'm interested in, because those are far more directly actionable than "type checking".

**Comment by tizoc** [comment]
Solved by #92. More can be added, but the base is there.
