### ISSUE TITLE
S31 release

### ISSUE THREAD

**Issue by maisiliym** [Shen-Language/shen-sources#98]
The new shen kernel (git-init'd [here](https://github.com/maisiliym/shen)) does not build; the klambda included in it has one unbalanced parentheses (ouch!) and errors on `shen.cond-code`. The current shen cannot build the klambda since it lacks some new functions. Has anyone been able to decipher the wonderful paper-scramblings of the great-sage-on-the-mountain-who-doesnt-care-for-linters-or-version-control?

**Comment by tizoc** [comment]
How are you trying to build it? The instructions in the README worked for me (producing a `shen-sbcl.exe` binary) when using SBCL 2.0.11 on macOS.

**Comment by tizoc** [comment]
Ok, just downloaded S31.zip again (which changed) and I now see the problem. I will let Mark know so that he uploads a new (and correct) archive.

**Comment by maisiliym** [comment]
There are non-technical people who use [lazygit](https://github.com/jesseduffield/lazygit) with great success. Perhaps someone can be convinced to give it a spin.

**Comment by tiancaiamao** [comment]
FYI, here is buggy https://github.com/maisiliym/shen/blob/ba76038d768ecaf19858130f9c877d1e384f2fa9/Sources/macros.shen#L23-L27

From an older download link from the Shen website, it was

```
(define defmacro-macro
  [defmacro F | Rest] -> (let Default [(protect X) -> (protect X)]
                              Def (eval [define F | (append Rest Default)])
                              Record (record-macro F (/. X (F X)))
                              F)
```

I found `(/. X (F X))`  is applying a symbol to a variable, reported it here https://groups.google.com/g/qilang/c/DySnw7zPscA

Now it's updated to  `(record-macro F (fn X))` now, but still not correct. I guess it should be `(fn F)` here... 
The official S31 source code is not released as git-managed? so people can't file PRs to fix them...

**Comment by tiancaiamao** [comment]
B.T.W, will @MTarver move the code here? or will the community version diverge from the S31 series?

**Comment by tizoc** [comment]
Hello, a new, corrected version of S31.zip is up, try that one.

**Comment by maisiliym** [comment]
Well done @tizoc  and, of course, great-master Tarver, who managed more elegance than anyone with just some paper and a pencil. Following in the footsteps of giants now, to make shen the next big thing. The [maisiliym/shen](https://github.com/maisiliym/shen) repo will stay updated until/unless a more official repo pops up. It now contains the latest update.
